title: Jake's First Site
author: Jake W
email: Not now
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This the awesome description that I am writing for my new page.  It is very promising...

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
